export const BELIBIZ_SERVICE_ROUTE: Record<string, string> = {
  LOGIN: "/user/login",
  REGISTER: "/user/register",
  BUSINESS_LISTING_PUBLIC: "/business-listing",
  BUSINESS_LISTING_USER: "/business-listing/user",
  BUSINESS_LISTING_ADMIN: "/admin/business-listing",
  PROFILE: "/user/update",
  ACCOUNT_SETTING: "/user/update/password",
  BUSINESS_LISTING_CREATE: "/business-listing/create",
  BUSINESS_LISTING_BYID: "/business-listing/detail",
  BUSINESS_LISTING_UPDATE: "/business-listing/update",
  BUSINESS_LISTING_UPDATE_ADMIN: "/admin/update/business-listing",
  USER_BY_ID: "/user/detail",
  MESSAGE_CREATE: "/message",
  UPLOAD_IMAGE: "/image/upload",
  GET_COUNTRIES: "/data/countries",
  GET_STATES: "/data/states",
  WISHLIST_CREATE: "/wishlist",
  WISHLIST: "/wishlist",
  WISHLIST_DELETE: "/wishlist",
  GET_USER_ADMIN: "/admin/user",
  UPDATE_PASSWORD_ADMIN: "/admin/update/password",
  BUSINESS_VALUATION: "/admin/business-valuation",
  BUSINESS_VALUATION_BYID: "/admin/business-valuation/detail",
  BUSINESS_VALUATION_POST: "/business-valuation",
  GET_MESSAGE: "/message",
  SUMMARY: "/summary",
  BUSINESS_LISTING_VIEW_STAT: "/business-listing/view/stats",
  BUSINESS_LISTING_VIEW: "/business-listing/view",
};

export const CLIENT_API_ROUTE: Record<string, string> = {
  LOGIN: "/api/login",
  REGISTER: "/api/register",
  PROFILE: "/api/profile",
  ACCOUNT_SETTING: "/api/account_setting",
  BUSINESS_LISTING_CREATE: "/api/business_listing_create",
  BUSINESS_LISTING_UPDATE: "/api/business_listing_update",
  BUSINESS_LISTING_UPDATE_ADMIN: "/api/business_listing_update_admin",
  MESSAGE_CREATE: "/api/message_create",
  BUSINESS_LISTING_WITH_FILTER: "/api/business_listing",
  BUSINESS_LISTING_REFETCH: "/api/business_listing_refetch",
  UPLOAD_IMAGE: "/api/upload_image",
  GET_STATES: "/api/states",
  WISHLIST_CREATE: "/api/wishlist_create",
  WISHLIST_DELETE: "/api/wishlist_delete",
  UPDATE_PASSWORD_ADMIN: "/api/update_password_admin",
  BUSINESS_VALUATION: "/api/business_valuation",
  PAGE_COUNTER: "/api/page_counter",
};
